services:
  vkmotion:
    image: yusufabm/vkmotion:latest
    container_name: vkmotion
    restart: unless-stopped
    ports:
      - "2095:3000"
    volumes:
      - vkmotion_db:/app/db
    environment:
      NODE_ENV: production
      PORT: "3000"
      DB_PATH: /app/db/vkmotion.db

volumes:
  vkmotion_db:
